import Head from "next/head";
import Home from "./Home";

export default function App({ products }: any) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto">
        <Home productData={products} />
      </main>
    </div>
  );
}

export const getServerSideProps = async () => {
  console.log("run");
  const response = await fetch(
    "https://e-commerce-nextjs-78991-default-rtdb.firebaseio.com/products.json"
  );
  const responseData = await response.json();

  console.log(responseData);

  const loadedProducts = [];

  for (const key in responseData) {
    loadedProducts.push({
      id: key,
      title: responseData[key].title,
      description: responseData[key].description,
      price: responseData[key].price,
      image1: responseData[key].image1,
      image2: responseData[key].image2,
      category: responseData[key].category,
    });
  }
  return {
    props: {
      products: loadedProducts,
    },
  };
};
